/*
  Auto-generated by Spline
*/

import { Suspense } from "react";
import { Canvas } from "@react-three/fiber";
import { Model } from "./scene";
import { Environment, OrbitControls } from "@react-three/drei";

const HeroComponent = () => {
  return (
    <Canvas style={{ height: "300px" }}>
      <Suspense fallback={null}>
        <Model />
      </Suspense>
    </Canvas>
  );
};

export default HeroComponent;
